"""
Django settings for grocerease project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from dotenv import load_dotenv


from pathlib import Path
import dj_database_url

load_dotenv()



BASE_DIR = Path(__file__).resolve().parent.parent





# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY', 'fallback-secret-key')
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# settings.py

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'grocerease-5xrs.onrender.com',  # Add your Render domain
    '.onrender.com',  # This allows all Render domains (useful for preview deployments)
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',
    'core',  
    'whitenoise.runserver_nostatic',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',   # ← add 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'grocerease.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'grocerease.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases



DATABASES = {
    'default': {
        'ENGINE':   'django.db.backends.postgresql',
        'NAME':     'postgres',
        'USER':     'postgres.mmdbbngsxcvekjwliowd',
        'PASSWORD': 'GrocerEase123',
        'HOST':     'aws-1-ap-southeast-1.pooler.supabase.com',
        'PORT':     '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
SESSION_COOKIE_AGE = 86400          # 1 day
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'

# CORS (for mobile app)
CORS_ALLOW_ALL_ORIGINS = False

# For production, specify exact origins:


CORS_ALLOWED_ORIGINS = [
    "https://grocerease-5xrs.onrender.com",  # Your web app
    "exp://192.168.1.x:19000",  # Expo development (your local IP)
    "exp://localhost:19000",     # Expo local
    "http://localhost:19006",     # React Native web
    "http://localhost:8081",      # Metro bundler
]

CORS_ALLOW_CREDENTIALS = True

# Add these headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Allow all hosts temporarily (for debugging)
ALLOWED_HOSTS = [
    'grocerease-5xrs.onrender.com',
    'localhost',
    '127.0.0.1',

]

# CSRF settings (important for POST requests from mobile)
CSRF_TRUSTED_ORIGINS = [
    'https://grocerease-5xrs.onrender.com',

]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'rjeanalie@gmail.com'
EMAIL_HOST_PASSWORD = 'ceqovoxsuhoayppp'
DEFAULT_FROM_EMAIL = 'rjeanalie@gmail.com'
EMAIL_TIMEOUT = 30

FRONTEND_URL = 'https://grocerease-5xrs.onrender.com/'

DEBUG = True


FRONTEND_URL = 'http://127.0.0.1:8000'
