# Generated by Django 4.2 on 2026-05-14 09:17

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaction_transactionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('stock_in_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_stock_in',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('stock_out_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(choices=[('sold', 'Sold'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('returned', 'Returned to Supplier')], max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_stock_out',
                'managed': False,
            },
        ),
    ]
